/*
 * SerialDefs.h
 *
 * Created: 8/25/2019 8:36:51 PM
 *  Author: km
 */ 


#ifndef SERIALDEFS_H_
#define SERIALDEFS_H_

#define SERIAL_STR_DEC 10
#define SERIAL_STR_HEX 16
#define SERIAL_STR_OCT 8

#define SERIAL_ASYNC			0x00
#define SERIAL_SYNC				_BV(UMSEL)

#define SERIAL_PARITY_DISABLED	0x00
#define SERIAL_PARITY_EVEN		_BV(UPM1)
#define SERIAL_PARITY_ODD		_BV(UPM1) |		_BV(UPM0)

#define SERIAL_STOP_BITS_1		0x00
#define SERIAL_STOP_BITS_2		_BV(USBS)

#define SERIAL_SIZE_BITS_5		0x00
#define SERIAL_SIZE_BITS_6										_BV(UCSZ0)
#define SERIAL_SIZE_BITS_7						_BV(UCSZ1)
#define SERIAL_SIZE_BITS_8						_BV(UCSZ1) |	_BV(UCSZ0)
#define SERIAL_SIZE_BITS_9		_BV(UCSZ2) |	_BV(UCSZ1) |	_BV(UCSZ0)

#define SERIAL_5N1 SERIAL_SIZE_BITS_5 | SERIAL_ASYNC | SERIAL_PARITY_DISABLED | SERIAL_STOP_BITS_1 
#define SERIAL_6N1 SERIAL_SIZE_BITS_6 | SERIAL_ASYNC | SERIAL_PARITY_DISABLED | SERIAL_STOP_BITS_1
#define SERIAL_7N1 SERIAL_SIZE_BITS_7 | SERIAL_ASYNC | SERIAL_PARITY_DISABLED | SERIAL_STOP_BITS_1
#define SERIAL_8N1 SERIAL_SIZE_BITS_8 | SERIAL_ASYNC | SERIAL_PARITY_DISABLED | SERIAL_STOP_BITS_1
#define SERIAL_5N2 SERIAL_SIZE_BITS_5 | SERIAL_ASYNC | SERIAL_PARITY_DISABLED | SERIAL_STOP_BITS_2
#define SERIAL_6N2 SERIAL_SIZE_BITS_6 | SERIAL_ASYNC | SERIAL_PARITY_DISABLED | SERIAL_STOP_BITS_2
#define SERIAL_7N2 SERIAL_SIZE_BITS_7 | SERIAL_ASYNC | SERIAL_PARITY_DISABLED | SERIAL_STOP_BITS_2
#define SERIAL_8N2 SERIAL_SIZE_BITS_8 | SERIAL_ASYNC | SERIAL_PARITY_DISABLED | SERIAL_STOP_BITS_2
#define SERIAL_5E1 SERIAL_SIZE_BITS_5 | SERIAL_ASYNC | SERIAL_PARITY_EVEN | SERIAL_STOP_BITS_1
#define SERIAL_6E1 SERIAL_SIZE_BITS_6 | SERIAL_ASYNC | SERIAL_PARITY_EVEN | SERIAL_STOP_BITS_1
#define SERIAL_7E1 SERIAL_SIZE_BITS_7 | SERIAL_ASYNC | SERIAL_PARITY_EVEN | SERIAL_STOP_BITS_1
#define SERIAL_8E1 SERIAL_SIZE_BITS_8 | SERIAL_ASYNC | SERIAL_PARITY_EVEN | SERIAL_STOP_BITS_1
#define SERIAL_5E2 SERIAL_SIZE_BITS_5 | SERIAL_ASYNC | SERIAL_PARITY_EVEN | SERIAL_STOP_BITS_2
#define SERIAL_6E2 SERIAL_SIZE_BITS_6 | SERIAL_ASYNC | SERIAL_PARITY_EVEN | SERIAL_STOP_BITS_2
#define SERIAL_7E2 SERIAL_SIZE_BITS_7 | SERIAL_ASYNC | SERIAL_PARITY_EVEN | SERIAL_STOP_BITS_2
#define SERIAL_8E2 SERIAL_SIZE_BITS_8 | SERIAL_ASYNC | SERIAL_PARITY_EVEN | SERIAL_STOP_BITS_2
#define SERIAL_5O1 SERIAL_SIZE_BITS_5 | SERIAL_ASYNC | SERIAL_PARITY_ODD  | SERIAL_STOP_BITS_1
#define SERIAL_6O1 SERIAL_SIZE_BITS_6 | SERIAL_ASYNC | SERIAL_PARITY_ODD  | SERIAL_STOP_BITS_1
#define SERIAL_7O1 SERIAL_SIZE_BITS_7 | SERIAL_ASYNC | SERIAL_PARITY_ODD  | SERIAL_STOP_BITS_1
#define SERIAL_8O1 SERIAL_SIZE_BITS_8 | SERIAL_ASYNC | SERIAL_PARITY_ODD  | SERIAL_STOP_BITS_1
#define SERIAL_5O2 SERIAL_SIZE_BITS_5 | SERIAL_ASYNC | SERIAL_PARITY_ODD  | SERIAL_STOP_BITS_2
#define SERIAL_6O2 SERIAL_SIZE_BITS_6 | SERIAL_ASYNC | SERIAL_PARITY_ODD  | SERIAL_STOP_BITS_2
#define SERIAL_7O2 SERIAL_SIZE_BITS_7 | SERIAL_ASYNC | SERIAL_PARITY_ODD  | SERIAL_STOP_BITS_2
#define SERIAL_8O2 SERIAL_SIZE_BITS_8 | SERIAL_ASYNC | SERIAL_PARITY_ODD  | SERIAL_STOP_BITS_2


#if !defined(UPE) && defined(PE)
#define UPE PE
#endif




#endif /* SERIALDEFS_H_ */